name: Deploy AuroraVoyages to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy App via SSH
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 1: Add SSH Private Key
    - name: Add SSH Key
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > key.pem
        chmod 600 key.pem

    # Step 2: SSH into Azure VM and deploy
    - name: Deploy Frontend & Backend via SSH
      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem auroravoyages@20.244.45.50 << 'EOF'
          echo "Pulling latest code..."
          cd ~/AuroraVoyagesClone
          git pull origin main

          echo ">>> Frontend setup"
          cd frontend
          npm install
          npm run build
          sudo cp -r build/* /var/www/html/aurora/frontend/build/
          sudo systemctl restart apache2

          echo ">>> Backend setup"
          cd ~/AuroraVoyagesClone/backend
          npm install
          sudo systemctl restart aurorabackend
        EOF

    # Step 3: Clean up SSH Key
    - name: Remove SSH Key
      run: rm key.pem
